import { Address } from "../common";
import { Bill } from "../bill";
import { PurchaseOrderComment } from "./comment";
import { PurchaseOrderItem } from "./item";
import { PurchaseReceive } from "./receive";
import { PurchaseTax } from "./tax";
import { SalesOrder } from "../sales-order";

export interface PurchaseOrder {
  adjustment: number;
  adjustmentDescription: string;
  attention: string;
  billedStatus: string;
  bills: Bill[];
  comments: PurchaseOrderComment[];
  createdTime: string;
  currencyCode: string;
  currencySymbol: string;
  date: string;
  deliveryAddress: Address;
  deliveryCustomerId: string;
  deliveryCustomerName: string;
  deliveryDate: string;
  deliveryOrgAddressId: string;
  exchangeRate: number;
  expectedDeliveryDate: string;
  isDropShipment: boolean;
  isInclusiveTax: boolean;
  items: PurchaseOrderItem[];
  lastModifiedTime: string;
  notes: string;
  orderStatus: string;
  purchaseorderId: string;
  purchaseorderNumber: string;
  purchasereceives: PurchaseReceive[];
  receivedStatus: string;
  referenceNumber: string;
  salesorderId: string;
  salesorders: SalesOrder[];
  shipVia: string;
  shipmentTrackingNumber?: string;
  status: string;
  subTotal: number;
  subTotalInclusiveOfTax: number;
  taxTotal: number;
  taxes: PurchaseTax[];
  terms: string;
  total: number;
}
